"""
@file commons.py
@author Antony Chiossi
"""


import string


def snowflake_to_base62(snowflake_id: int) -> str:
    """
    This function converts a snowflake ID (represented in hexadecimal) to a base62 string.

    :param snowflake_id: The snowflake_id parameter is a string representing a unique identifier
    generated by Twitter's Snowflake algorithm. It is typically a 64-bit integer represented in
    hexadecimal format
    :return: a base62 representation of a given snowflake ID.
    """
    print(snowflake_id, int(str(snowflake_id), 16))
    base62_alphabet = string.digits + string.ascii_uppercase + string.ascii_lowercase
    base10 = int(str(snowflake_id), 16)
    base62 = []
    while base10 > 0:
        # Divide the base10 number by 62 using bitwise right shift operator (>>),
        # and get the remainder using bitwise AND operator (&) with a mask of 0x3F.
        base10, remainder = base10 >> 6, base10 & 0x3F
        base62.append(base62_alphabet[remainder])
    print(len(base62))
    return "".join(reversed(base62))
